name: Atualizacao de banco de dados imobiliarios

on:
  schedule:
    - cron: "0 21 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Instalar requirements e driver
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager

      - name: Rodar o scraper
        run: python scripts/web_scraping.py

      - name: Commit e push do CSV atualizado
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dados/dados_imoveis.csv || echo "Nada pra commitar"
          git commit -m "Atualiza dados automaticamente [ci skip]" || echo "Sem mudanças pra commitar"
          git push
